"""
Django settings for encompass project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import json
import socket
import ldap
from django_auth_ldap.config import (
    LDAPSearch,
    NestedActiveDirectoryGroupType,
    ActiveDirectoryGroupType,
    GroupOfNamesType,
    PosixGroupType,
)
from django_auth_ldap.config import LDAPGroupQuery
from . import tools
from . import runtime_settings


def env_json(name, default):
    """imports a JSON object and create a dictionary or list from it"""
    return json.loads(os.environ.get(name, json.dumps(default)))


def env_log_level(name, default="ERROR"):
    """Return a validated logging level from environment."""
    valid_levels = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}
    level = str(os.environ.get(name, default)).strip().upper()
    return level if level in valid_levels else default


def env_choice(name, default, allowed):
    """Return a validated lowercase choice from environment."""
    value = str(os.environ.get(name, default)).strip().lower()
    if value not in allowed:
        allowed_values = ", ".join(sorted(allowed))
        raise SystemExit(f"{name} must be one of: {allowed_values}")
    return value


def env_float(name, default):
    """Return a validated float value from environment."""
    raw = str(os.environ.get(name, default)).strip()
    try:
        return float(raw)
    except (TypeError, ValueError):
        raise SystemExit(f"{name} must be a valid number") from None


def env_bool(name, default=False):
    """Return a validated boolean value from environment."""
    raw = str(os.environ.get(name, str(default))).strip().lower()
    if raw in {"1", "true", "yes", "on"}:
        return True
    if raw in {"0", "false", "no", "off", ""}:
        return False
    raise SystemExit(f"{name} must be a boolean (true/false)")


USE_AUTH_LDAP = False
FEATURE_BRANCH = False
ENC_OVERLAPPING_DEFINITIONS_ENABLED = False
UNCLASSIFIED_HOSTS_ENABLED = True
DEMO_MODE = env_json("DEMO_MODE", False)
USE_AUTH_MYSQL = True
if DEMO_MODE not in [True, False]:
    print("DEMO_MODE must be True or False")
    raise SystemExit(1)

# Group identifiers used across the app.
# In MySQL mode these are plain Django group names.
# In LDAP mode they are overridden below with full DNs.
ENC_ADMIN_GROUP = os.environ.get("ENC_ADMIN_GROUP", "enc_admin")
ENC_VIEWER_GROUP = os.environ.get("ENC_VIEWER_GROUP", "enc_viewer")
READ_ONLY_GROUPS = [ENC_ADMIN_GROUP, ENC_VIEWER_GROUP]
ADMIN_ONLY_GROUPS = [ENC_ADMIN_GROUP]

WATERMARK = tools.get_file_content("/code/watermark")
CURRENT_VERSION = tools.get_file_content("/code/version")

# SECURITY WARNING: don't run with debug turned on production!
DEBUG = env_json("DEBUG", False)

HOME_DIR = "/code"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")
TRY_AGAIN = "Please try again"
ERROR_HTML = "error.html"
UNLOGGED = "Not logged in"
ENCAPSULE_SYNC_WARNING_MESSAGE = (
    "Data was saved, committed, and pushed to Git, but synchronization to enCapsule failed. "
    "enCapsule will pull the latest data when it becomes available."
)
ENCAPSULE_ASYNC_INFO_MESSAGE = (
    "Data was saved, committed, and pushed to Git. Synchronization to enCapsule runs "
    "asynchronously; check logs for final sync status."
)
NO_CHANGES_INFO_MESSAGE = (
    "No YAML changes were detected, so no Git push/synchronization was required."
)

# SECURITY WARNING: keep the secret key used in production secret!
# The key can be a secret in Nomad:
# https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
SECRET_KEY_FALLBACKS = ["w%-5r)w-d!89x94!q8ds_-u6bf*s0!k!-$n*cm6x^-+m#o-t29"]
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

ALLOWED_CIDR_NETS = env_json("ALLOWED_CIDR_NETS", [])
CSRF_TRUSTED_ORIGINS = env_json("CSRF_TRUSTED_ORIGINS", [])
local_proxy_origins = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "https://localhost:8443",
    "https://127.0.0.1:8443",
    "https://localhost:8444",
    "https://127.0.0.1:8444",
]
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS + local_proxy_origins))

try:
    LOCAL_ADDR = socket.getaddrinfo(socket.getfqdn(), None, socket.AF_INET)[0][4][0]
except socket.gaierror:
    LOCAL_ADDR = "127.0.0.1"

DEFAULT_LOCAL_ALLOWED_HOSTS = list({"localhost", "127.0.0.1", LOCAL_ADDR})
ALLOWED_HOSTS = env_json("ALLOWED_HOSTS", []) + DEFAULT_LOCAL_ALLOWED_HOSTS
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# Applications definition
INSTALLED_APPS = (
    # "oauth2_provider",  # DISABLED in requirements.txt
    "encompass",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
)

SITE_ID = 1
LOGIN_REDIRECT_URL = "/encompass"

MIDDLEWARE = (
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "allow_cidr.middleware.AllowCIDRMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
)

CORS_ALLOWED_ORIGINS = env_json("CORS_ALLOWED_ORIGINS", [])
ROOT_URLCONF = "encompass.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# this can be used in conjunction with Apache
WSGI_APPLICATION = "encompass.wsgi.application"

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
required_mysql_env = ("MYSQL_NODES", "MYSQL_DB", "MYSQL_USER")
missing_mysql_env = [name for name in required_mysql_env if not os.environ.get(name)]
if missing_mysql_env:
    raise SystemExit(
        "Missing required MySQL environment variables: " + ", ".join(missing_mysql_env)
    )

_db_options: dict = {"charset": "utf8mb4"}
if runtime_settings.mysql_use_socket():
    _db_options["unix_socket"] = runtime_settings.HAPROXY_MYSQL_SOCKET
    MYSQL_HOST = ""
    MYSQL_PORT: int | str = ""
else:
    MYSQL_HOST, MYSQL_PORT = runtime_settings.mysql_connection_endpoint()

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ["MYSQL_DB"],
        "USER": os.environ["MYSQL_USER"],
        "PASSWORD": os.environ.get("MYSQL_PASSWORD", ""),
        "HOST": MYSQL_HOST,
        "PORT": MYSQL_PORT,
        "OPTIONS": _db_options,
    }
}

USE_AUTH_LDAP = runtime_settings.ldap_auth_enabled()

# Logging section
ENCOMPASS_LOG_LEVEL = env_log_level(
    "ENCOMPASS_LOGGING",
    "DEBUG" if DEBUG else "INFO",
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "ignore_healthz": {
            "()": "encompass.logging_filters.IgnoreHealthzFilter",
        },
    },
    "handlers": {
        "stream_to_console": {
            "level": ENCOMPASS_LOG_LEVEL,
            "class": "logging.StreamHandler",
            "filters": ["ignore_healthz"],
        },
    },
    "loggers": {
        "django.server": {
            "handlers": ["stream_to_console"],
            "level": ENCOMPASS_LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["stream_to_console"],
            "level": ENCOMPASS_LOG_LEVEL,
            "propagate": False,
        },
        "encompass": {
            "handlers": ["stream_to_console"],
            "level": ENCOMPASS_LOG_LEVEL,
            "propagate": False,
        },
    },
}


AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

if USE_AUTH_LDAP:
    # LDAP configuration
    #
    # group shuold be added also to AUTH_LDAP_USER_FLAGS_BY_GROUP, AUTH_LDAP_REQUIRE_GROUP
    # and in the function determine_group() in encompass/encompass/tools.py
    LDAP_PROF = (
        runtime_settings.get_text(
            "LDAP_PROFILE", runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_PROFILE"]
        )
        .strip()
        .lower()
        or "ad"
    )
    if LDAP_PROF not in {"ad", "openldap"}:
        raise SystemExit("LDAP_PROFILE must be one of: ad, openldap")

    GROUP_RDN_ATTR = runtime_settings.get_text(
        "LDAP_GROUP_RDN_ATTR",
        runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_GROUP_RDN_ATTR"],
    ).strip() or ("CN" if LDAP_PROF == "ad" else "cn")
    LDAP_GROUPS_BASE_DN = runtime_settings.get_text(
        "LDAP_GROUPS_BASE_DN",
        runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_GROUPS_BASE_DN"],
    )
    ENC_ADMIN_GROUP = f"{GROUP_RDN_ATTR}=enc_admin,{LDAP_GROUPS_BASE_DN}"
    ENC_VIEWER_GROUP = f"{GROUP_RDN_ATTR}=enc_viewer,{LDAP_GROUPS_BASE_DN}"

    USER_SEARCH_FILTER = runtime_settings.get_text(
        "LDAP_USER_SEARCH_FILTER",
        runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_USER_SEARCH_FILTER"],
    ).strip() or (
        "(sAMAccountName=%(user)s)" if LDAP_PROF == "ad" else "(uid=%(user)s)"
    )
    GROUP_SEARCH_FILTER = runtime_settings.get_text(
        "LDAP_GROUP_SEARCH_FILTER",
        runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_GROUP_SEARCH_FILTER"],
    ).strip() or (
        "(objectClass=group)" if LDAP_PROF == "ad" else "(objectClass=groupOfNames)"
    )

    GROUP_TYPE_NAME = "ad_nested" if LDAP_PROF == "ad" else "groupofnames"
    group_type_map = {
        "ad_nested": NestedActiveDirectoryGroupType,
        "ad": ActiveDirectoryGroupType,
        "groupofnames": GroupOfNamesType,
        "posix": PosixGroupType,
    }
    AUTHENTICATION_BACKENDS = (
        "django.contrib.auth.backends.ModelBackend",
        "django_auth_ldap.backend.LDAPBackend",
    )
    AUTH_LDAP_USER_FLAGS_BY_GROUP = {
        "is_superuser": [ENC_ADMIN_GROUP],
        "is_viewer": [ENC_VIEWER_GROUP],
    }
    AUTH_LDAP_REQUIRE_GROUP = LDAPGroupQuery(ENC_ADMIN_GROUP) | LDAPGroupQuery(
        ENC_VIEWER_GROUP
    )
    LDAP_PROTO = (
        runtime_settings.get_text(
            "LDAP_PROTO", runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_PROTO"]
        )
        .strip()
        .lower()
    )
    if LDAP_PROTO not in {"ldap", "ldaps"}:
        raise SystemExit("LDAP_PROTO must be one of: ldap, ldaps")
    LDAP_SERVER = runtime_settings.get_text(
        "LDAP_SERVER", runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_SERVER"]
    ).strip()
    LDAP_PORT = runtime_settings.get_text(
        "LDAP_PORT", runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_PORT"]
    ).strip()
    if not LDAP_PORT.isdigit():
        raise SystemExit("LDAP_PORT must be numeric")

    AUTH_LDAP_SERVER_URI = (
        f"{LDAP_PROTO}://{LDAP_SERVER}:{LDAP_PORT}"  # pylint: disable=line-too-long
    )
    AUTH_LDAP_BIND_DN = runtime_settings.get_text(
        "LDAP_BIND_DN", runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_BIND_DN"]
    )
    AUTH_LDAP_BIND_PASSWORD = runtime_settings.get_text(
        "LDAP_BIND_PASSWORD", runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_BIND_PASSWORD"]
    )
    ldap_network_timeout = env_float("LDAP_NETWORK_TIMEOUT", "2")
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_DEBUG_LEVEL: 1,  # pylint: disable=no-member
        ldap.OPT_REFERRALS: 0,  # pylint: disable=no-member
        ldap.OPT_NETWORK_TIMEOUT: ldap_network_timeout,  # pylint: disable=no-member
    }
    LDAP_OPT_TIMEOUT = getattr(ldap, "OPT_TIMEOUT", None)
    if LDAP_OPT_TIMEOUT is not None:
        AUTH_LDAP_CONNECTION_OPTIONS[LDAP_OPT_TIMEOUT] = ldap_network_timeout
    ldap_tls_skip_verify = runtime_settings.ldap_tls_skip_verify_enabled()
    LDAP_OPT_X_TLS_REQUIRE_CERT = getattr(ldap, "OPT_X_TLS_REQUIRE_CERT", None)
    LDAP_OPT_X_TLS_NEVER = getattr(ldap, "OPT_X_TLS_NEVER", 0)
    LDAP_OPT_X_TLS_DEMAND = getattr(ldap, "OPT_X_TLS_DEMAND", 2)
    AUTH_LDAP_GLOBAL_OPTIONS = {}
    if LDAP_OPT_X_TLS_REQUIRE_CERT is not None:
        AUTH_LDAP_GLOBAL_OPTIONS[LDAP_OPT_X_TLS_REQUIRE_CERT] = (
            LDAP_OPT_X_TLS_NEVER if ldap_tls_skip_verify else LDAP_OPT_X_TLS_DEMAND
        )
    # User and group search objects and types
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        runtime_settings.get_text(
            "LDAP_USER_BASE_DN",
            runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_USER_BASE_DN"],
        ),
        ldap.SCOPE_SUBTREE,  # pylint: disable=no-member
        USER_SEARCH_FILTER,
    )
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        LDAP_GROUPS_BASE_DN,
        ldap.SCOPE_SUBTREE,  # pylint: disable=no-member
        GROUP_SEARCH_FILTER,
    )
    AUTH_LDAP_GROUP_TYPE = group_type_map[GROUP_TYPE_NAME]()
    # Cache settings
    AUTH_LDAP_CACHE_GROUPS = True
    AUTH_LDAP_GROUP_CACHE_TIMEOUT = 300
    AUTH_LDAP_CACHE_TIMEOUT = 3600
    # What to do once the user is authenticated
    try:
        AUTH_LDAP_USER_ATTR_MAP = json.loads(
            runtime_settings.effective_ldap_user_attr_map_text(LDAP_PROF)
        )
    except json.JSONDecodeError as err:
        raise SystemExit("LDAP_USER_ATTR_MAP must be valid JSON") from err
    if not isinstance(AUTH_LDAP_USER_ATTR_MAP, dict):
        raise SystemExit("LDAP_USER_ATTR_MAP must be a JSON object")
    AUTH_LDAP_FIND_GROUP_PERMS = True
    AUTH_LDAP_MIRROR_GROUPS = runtime_settings.ldap_mirror_groups_enabled()
    LDAP_LOGGING_LEVEL = (
        str(
            runtime_settings.get_text(
                "LDAP_LOGGING",
                runtime_settings.LDAP_TEXT_DEFAULTS["LDAP_LOGGING"],
            )
        )
        .strip()
        .upper()
    )
    if LDAP_LOGGING_LEVEL not in {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}:
        LDAP_LOGGING_LEVEL = "ERROR"
    LOGGING["loggers"]["django_auth_ldap"] = {
        "handlers": ["stream_to_console"],
        "level": LDAP_LOGGING_LEVEL,
        "propagate": False,
    }
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", "en-us")
TIME_ZONE = os.environ.get("TIME_ZONE", "UTC")
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(HOME_DIR, "static", "static")
