"""
Django settings for encompass project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import json
import socket
import ldap
from django_auth_ldap.config import (
    LDAPSearch,
    NestedActiveDirectoryGroupType,
    ActiveDirectoryGroupType,
    GroupOfNamesType,
    PosixGroupType,
)
from django_auth_ldap.config import LDAPGroupQuery
from . import tools


def env_json(name, default):
    """imports a JSON object and create a dictionary or list from it"""
    return json.loads(os.environ.get(name, json.dumps(default)))


def env_log_level(name, default="ERROR"):
    """Return a validated logging level from environment."""
    valid_levels = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}
    level = str(os.environ.get(name, default)).strip().upper()
    return level if level in valid_levels else default


def env_log_level_preferred(preferred_name, fallback_name, default="ERROR"):
    """Return preferred log level env var, with fallback for backward compatibility."""
    if os.environ.get(preferred_name):
        return env_log_level(preferred_name, default)
    return env_log_level(fallback_name, default)


def env_choice(name, default, allowed):
    """Return a validated lowercase choice from environment."""
    value = str(os.environ.get(name, default)).strip().lower()
    if value not in allowed:
        allowed_values = ", ".join(sorted(allowed))
        raise SystemExit(f"{name} must be one of: {allowed_values}")
    return value


USE_AUTH_LDAP = env_json("AUTH_LDAP_ENABLED", False)
USE_AUTH_MYSQL = env_json("AUTH_MYSQL_ENABLED", False)
FEATURE_BRANCH = env_json("FEATURE_BRANCH", False)
UNCLASSIFIED_HOSTS_ENABLED = env_json("UNCLASSIFIED_HOSTS_ENABLED", True)
DEMO_MODE = env_json("DEMO_MODE", False)
PUPPET_ENVIRONMENTS = env_json("PUPPET_ENVIRONMENTS", ["production"])
if USE_AUTH_LDAP not in [True, False] or USE_AUTH_MYSQL not in [True, False]:
    print("Either AUTH_LDAP_ENABLED or AUTH_MYSQL_ENABLED must be True or False")
    raise SystemExit(1)
if USE_AUTH_LDAP == USE_AUTH_MYSQL:
    print("Both AUTH_LDAP_ENABLED and AUTH_MYSQL_ENABLED cannot be the same")
    raise SystemExit(1)
if FEATURE_BRANCH not in [True, False]:
    print("FEATURE_BRANCH must be True or False")
    raise SystemExit(1)
if UNCLASSIFIED_HOSTS_ENABLED not in [True, False]:
    print("UNCLASSIFIED_HOSTS_ENABLED must be True or False")
    raise SystemExit(1)
if DEMO_MODE not in [True, False]:
    print("DEMO_MODE must be True or False")
    raise SystemExit(1)
if not isinstance(PUPPET_ENVIRONMENTS, list):
    print("PUPPET_ENVIRONMENTS must be a JSON list")
    raise SystemExit(1)
PUPPET_ENVIRONMENTS = [str(item).strip() for item in PUPPET_ENVIRONMENTS if str(item).strip()]

# Group identifiers used across the app.
# In MySQL mode these are plain Django group names.
# In LDAP mode they are overridden below with full DNs.
ENC_ADMIN_GROUP = os.environ.get("ENC_ADMIN_GROUP", "enc_admin")
ENC_VIEWER_GROUP = os.environ.get("ENC_VIEWER_GROUP", "enc_viewer")
READ_ONLY_GROUPS = [ENC_ADMIN_GROUP, ENC_VIEWER_GROUP]
ADMIN_ONLY_GROUPS = [ENC_ADMIN_GROUP]

WATERMARK = tools.get_file_content("/code/watermark")
CURRENT_VERSION = tools.get_file_content("/code/version")

# SECURITY WARNING: don't run with debug turned on production!
DEBUG = env_json("DEBUG", False)

HOME_DIR = "/code"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")
TRY_AGAIN = "Please try again"
ERROR_HTML = "error.html"
UNLOGGED = "Not logged in"
ENCAPSULE_SYNC_WARNING_MESSAGE = (
    "Data was saved, committed, and pushed to Git, but synchronization to enCapsule failed. "
    "enCapsule will pull the latest data when it becomes available."
)
ENCAPSULE_ASYNC_INFO_MESSAGE = (
    "Data was saved, committed, and pushed to Git. Synchronization to enCapsule runs "
    "asynchronously; check logs for final sync status."
)
NO_CHANGES_INFO_MESSAGE = (
    "No YAML changes were detected, so no Git push/synchronization was required."
)

# SECURITY WARNING: keep the secret key used in production secret!
# The key can be a secret in Nomad:
# https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
SECRET_KEY = os.environ["SECRET_KEY"]
SECRET_KEY_FALLBACKS = ["w%-5r)w-d!89x94!q8ds_-u6bf*s0!k!-$n*cm6x^-+m#o-t29"]
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

ALLOWED_CIDR_NETS = env_json("ALLOWED_CIDR_NETS", [])
CSRF_TRUSTED_ORIGINS = env_json("CSRF_TRUSTED_ORIGINS", [])
local_proxy_origins = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "https://localhost:8443",
    "https://127.0.0.1:8443",
    "https://localhost:8444",
    "https://127.0.0.1:8444",
]
CSRF_TRUSTED_ORIGINS = list(
    dict.fromkeys(CSRF_TRUSTED_ORIGINS + local_proxy_origins)
)

ALLOWED_HOSTS = env_json("ALLOWED_HOSTS", []) + [
    socket.getaddrinfo(socket.getfqdn(), None, socket.AF_INET)[0][4][0],
]

# Applications definition
INSTALLED_APPS = (
    # "oauth2_provider",  # DISABLED in requirements.txt
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
)

SITE_ID = 1
LOGIN_REDIRECT_URL = "/encompass"

MIDDLEWARE = (
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "allow_cidr.middleware.AllowCIDRMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
)

CORS_ALLOWED_ORIGINS = env_json("CORS_ALLOWED_ORIGINS", [])
ROOT_URLCONF = "encompass.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# this can be used in conjunction with Apache
WSGI_APPLICATION = "encompass.wsgi.application"

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
required_mysql_env = ("MYSQL_HOST", "MYSQL_DB", "MYSQL_USER")
missing_mysql_env = [name for name in required_mysql_env if not os.environ.get(name)]
if missing_mysql_env:
    raise SystemExit(
        "Missing required MySQL environment variables: " + ", ".join(missing_mysql_env)
    )

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ["MYSQL_DB"],
        "USER": os.environ["MYSQL_USER"],
        "PASSWORD": os.environ.get("MYSQL_PASSWORD", ""),
        "HOST": os.environ["MYSQL_HOST"],
        "PORT": int(os.environ.get("MYSQL_PORT", "3306")),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

# Logging section
ENCOMPASS_LOG_LEVEL = env_log_level(
    "ENCOMPASS_LOGGING",
    "DEBUG" if DEBUG else "INFO",
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "ignore_healthz": {
            "()": "encompass.logging_filters.IgnoreHealthzFilter",
        },
    },
    "handlers": {
        "stream_to_console": {
            "level": ENCOMPASS_LOG_LEVEL,
            "class": "logging.StreamHandler",
            "filters": ["ignore_healthz"],
        },
    },
    "loggers": {
        "django.server": {
            "handlers": ["stream_to_console"],
            "level": ENCOMPASS_LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["stream_to_console"],
            "level": ENCOMPASS_LOG_LEVEL,
            "propagate": False,
        },
        "encompass": {
            "handlers": ["stream_to_console"],
            "level": ENCOMPASS_LOG_LEVEL,
            "propagate": False,
        },
    },
}


if USE_AUTH_LDAP:
    # LDAP configuration
    #
    # group shuold be added also to AUTH_LDAP_USER_FLAGS_BY_GROUP, AUTH_LDAP_REQUIRE_GROUP
    # and in the function determine_group() in encompass/encompass/tools.py
    LDAP_PROF = env_choice("LDAP_PROFILE", "ad", {"ad", "openldap"})
    group_rdn_attr = (
        os.environ.get("LDAP_GROUP_RDN_ATTR", "").strip()
        or ("CN" if LDAP_PROF == "ad" else "cn")
    )
    ENC_ADMIN_GROUP = f"{group_rdn_attr}=enc_admin,{os.environ['LDAP_GROUPS_BASE_DN']}"
    ENC_VIEWER_GROUP = f"{group_rdn_attr}=enc_viewer,{os.environ['LDAP_GROUPS_BASE_DN']}"

    user_search_filter = (
        os.environ.get("LDAP_USER_SEARCH_FILTER", "").strip()
        or ("(sAMAccountName=%(user)s)" if LDAP_PROF == "ad" else "(uid=%(user)s)")
    )
    group_search_filter = (
        os.environ.get("LDAP_GROUP_SEARCH_FILTER", "").strip()
        or ("(objectClass=group)" if LDAP_PROF == "ad" else "(objectClass=groupOfNames)")
    )

    DEFAULT_GOUP_TYPE = "ad_nested" if LDAP_PROF == "ad" else "groupofnames"
    group_type_name = (os.environ.get("LDAP_GROUP_TYPE", "").strip().lower() or DEFAULT_GOUP_TYPE)
    if group_type_name not in {"ad_nested", "ad", "groupofnames", "posix"}:
        raise SystemExit("LDAP_GROUP_TYPE must be one of: ad_nested, ad, groupofnames, posix")
    group_type_map = {
        "ad_nested": NestedActiveDirectoryGroupType,
        "ad": ActiveDirectoryGroupType,
        "groupofnames": GroupOfNamesType,
        "posix": PosixGroupType,
    }
    AUTHENTICATION_BACKENDS = (
        "django_auth_ldap.backend.LDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
    )
    AUTH_LDAP_USER_FLAGS_BY_GROUP = {
        "is_superuser": [ENC_ADMIN_GROUP],
        "is_viewer": [ENC_VIEWER_GROUP],
    }
    AUTH_LDAP_REQUIRE_GROUP = (
        LDAPGroupQuery(ENC_ADMIN_GROUP)
        | LDAPGroupQuery(ENC_VIEWER_GROUP)
    )
    AUTH_LDAP_SERVER_URI = f"{os.environ['LDAP_PROTO']}://{os.environ['LDAP_SERVER']}:{os.environ['LDAP_PORT']}"  # pylint: disable=line-too-long
    AUTH_LDAP_BIND_DN = os.environ["LDAP_BIND_DN"]
    AUTH_LDAP_BIND_PASSWORD = os.environ["LDAP_BIND_PASSWORD"]
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_DEBUG_LEVEL: 1,  # pylint: disable=no-member
        ldap.OPT_REFERRALS: 0,  # pylint: disable=no-member
    }
    AUTH_LDAP_GLOBAL_OPTIONS = {
        ldap.OPT_X_TLS_REQUIRE_CERT: False,  # pylint: disable=no-member
    }
    # User and group search objects and types
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        os.environ["LDAP_USER_BASE_DN"],
        ldap.SCOPE_SUBTREE,  # pylint: disable=no-member
        user_search_filter,
    )
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        os.environ["LDAP_GROUPS_BASE_DN"],
        ldap.SCOPE_SUBTREE,  # pylint: disable=no-member
        group_search_filter,
    )
    AUTH_LDAP_GROUP_TYPE = group_type_map[group_type_name]()
    # Cache settings
    AUTH_LDAP_CACHE_GROUPS = True
    AUTH_LDAP_GROUP_CACHE_TIMEOUT = 300
    AUTH_LDAP_CACHE_TIMEOUT = 3600
    # What to do once the user is authenticated
    AUTH_LDAP_USER_ATTR_MAP = env_json(
        "LDAP_USER_ATTR_MAP",
        {
            "first_name": "givenName",
            "last_name": "sn",
            "email": "mail",
        },
    )
    AUTH_LDAP_FIND_GROUP_PERMS = True
    LOGGING['loggers']['django_auth_ldap'] = {
        "handlers": ["stream_to_console"],
            "level": env_log_level_preferred(
                "LDAP_AUTH_DEBUG",
                "LDAP_LOGGING",
                env_log_level("AUTH_DEBUG", "ERROR"),
            ),
        "propagate": False,
    }
elif USE_AUTH_MYSQL:
    # Local Django authentication
    #
    AUTHENTICATION_BACKENDS = (
        "django.contrib.auth.backends.ModelBackend",
    )

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", "en-us")
TIME_ZONE = os.environ.get("TIME_ZONE", "UTC")
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(HOME_DIR, "static", "static")
