"""
Django settings for encompass project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

import os
import json
import socket
import ldap
from django_auth_ldap.config import LDAPSearch, NestedActiveDirectoryGroupType
from django_auth_ldap.config import LDAPGroupQuery
from . import tools


def env_json(name, default):
    """imports a JSON object and create a dictionary or list from it"""
    return json.loads(os.environ.get(name, json.dumps(default)))


USE_AUTH_LDAP = env_json("AUTH_LDAP_ENABLED", False)
USE_AUTH_SQLITE = env_json("AUTH_SQLITE_ENABLED", False)
if USE_AUTH_LDAP not in [True, False] or USE_AUTH_SQLITE not in [True, False]:
    print("Either AUTH_LDAP_ENABLED or AUTH_SQLITE_ENABLED must be True or False")
    raise SystemExit(1)
if USE_AUTH_LDAP == USE_AUTH_SQLITE:
    print("Both AUTH_LDAP_ENABLED and AUTH_SQLITE_ENABLED cannot be the same")
    raise SystemExit(1)

WATERMARK = tools.get_file_content("/local/watermark")
CURRENT_VERSION = tools.get_file_content("/local/version")
IS_DRY_RUN = True if "TEST" in WATERMARK or "UAT" in WATERMARK else False

IS_MULTIPROCESS = True  # dhashboard is difficult to debug in multiprocess mode

# SECURITY WARNING: don't run with debug turned on production!
DEBUG = env_json("DEBUG", False)

HOME_DIR = "/code"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")
CDS_URL = "https://cds.geant.org/tformator"
TRY_AGAIN = "Please try again"
ERROR_HTML = "error.html"
TEXT_HTML = "text/html"
UNLOGGED = "Not logged in"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = "/static/"

# SECURITY WARNING: keep the secret key used in production secret!
# The key can be a secret in Nomad:
# https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
SECRET_KEY = os.environ["SECRET_KEY"]
SECRET_KEY_FALLBACKS = ["w%-5r)w-d!89x94!q8ds_-u6bf*s0!k!-$n*cm6x^-+m#o-t29"]
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

ALLOWED_CIDR_NETS = env_json("ALLOWED_CIDR_NETS", [])
CSRF_TRUSTED_ORIGINS = env_json("CSRF_TRUSTED_ORIGINS", [])
local_proxy_origins = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "https://localhost:8443",
    "https://127.0.0.1:8443",
    "https://localhost:8444",
    "https://127.0.0.1:8444",
]
CSRF_TRUSTED_ORIGINS = list(
    dict.fromkeys(CSRF_TRUSTED_ORIGINS + local_proxy_origins)
)

ALLOWED_HOSTS = env_json("ALLOWED_HOSTS", []) + [
    socket.getaddrinfo(socket.getfqdn(), None, socket.AF_INET)[0][4][0],
]

# Applications definition
INSTALLED_APPS = (
    # "oauth2_provider",  # DISABLED in requirements.txt
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
)

SITE_ID = 1
LOGIN_REDIRECT_URL = "/encompass"

MIDDLEWARE = (
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "allow_cidr.middleware.AllowCIDRMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
)

CORS_ALLOWED_ORIGINS = env_json("CORS_ALLOWED_ORIGINS", [])
ROOT_URLCONF = "encompass.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# this can be used in conjunction with Apache
WSGI_APPLICATION = "encompass.wsgi.application"

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "/sqlite/db.sqlite3",
    }
}

if USE_AUTH_LDAP:
    # LDAP configuration
    #
    # group shuold be added also to AUTH_LDAP_USER_FLAGS_BY_GROUP, AUTH_LDAP_REQUIRE_GROUP
    # and in the function determine_group() in encompass/encompass/tools.py
    ENC_ADMIN_GROUP = f"CN=enc_admin,{os.environ['LDAP_GROUPS_BASE_DN']}"
    ENC_USER_GROUP = f"CN=enc_user,{os.environ['LDAP_GROUPS_BASE_DN']}"
    ENC_VIEWER_GROUP = f"CN=enc_viewer,{os.environ['LDAP_GROUPS_BASE_DN']}"
    AUTHENTICATION_BACKENDS = (
        "django_auth_ldap.backend.LDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
    )
    AUTH_LDAP_USER_FLAGS_BY_GROUP = {
        "is_superuser": [ENC_ADMIN_GROUP],
        "is_user": [ENC_USER_GROUP],
        "is_viewer": [ENC_VIEWER_GROUP],
    }
    AUTH_LDAP_REQUIRE_GROUP = (
        LDAPGroupQuery(ENC_ADMIN_GROUP)
        | LDAPGroupQuery(ENC_USER_GROUP)
        | LDAPGroupQuery(ENC_VIEWER_GROUP)
    )
    AUTH_LDAP_SERVER_URI = f"{os.environ['LDAP_PROTO']}://{os.environ['LDAP_SERVER']}:{os.environ['LDAP_PORT']}"  # pylint: disable=line-too-long
    AUTH_LDAP_BIND_DN = os.environ["LDAP_BIND_DN"]
    AUTH_LDAP_BIND_PASSWORD = os.environ["LDAP_BIND_PASSWORD"]
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_DEBUG_LEVEL: 1,  # pylint: disable=no-member
        ldap.OPT_REFERRALS: 0,  # pylint: disable=no-member
    }
    AUTH_LDAP_GLOBAL_OPTIONS = {
        ldap.OPT_X_TLS_REQUIRE_CERT: False,  # pylint: disable=no-member
    }
    # User and group search objects and types
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        os.environ["LDAP_USER_BASE_DN"],
        ldap.SCOPE_SUBTREE,  # pylint: disable=no-member
        "(sAMAccountName=%(user)s)",
    )
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        os.environ["LDAP_GROUPS_BASE_DN"],
        ldap.SCOPE_SUBTREE,  # pylint: disable=no-member
        "(objectClass=group)",
    )
    AUTH_LDAP_GROUP_TYPE = NestedActiveDirectoryGroupType()
    # Cache settings
    AUTH_LDAP_CACHE_GROUPS = True
    AUTH_LDAP_GROUP_CACHE_TIMEOUT = 300
    AUTH_LDAP_CACHE_TIMEOUT = 3600
    # What to do once the user is authenticated
    AUTH_LDAP_USER_ATTR_MAP = env_json(
        "LDAP_USER_ATTR_MAP",
        {
            "first_name": "givenName",
            "last_name": "sn",
            "email": "mail",
        },
    )
    AUTH_LDAP_FIND_GROUP_PERMS = True
elif USE_AUTH_SQLITE:
    # SQLite authentication
    #
    AUTHENTICATION_BACKENDS = "django.contrib.auth.backends.ModelBackend"

# Logging section
if DEBUG:
    LOG_LEVEL = "DEBUG"
else:
    LOG_LEVEL = "INFO"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "ignore_healthz": {
            "()": "encompass.logging_filters.IgnoreHealthzFilter",
        },
    },
    "handlers": {
        "stream_to_console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "filters": ["ignore_healthz"],
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
        },
    },
    "loggers": {
        "django.server": {
            "handlers": ["stream_to_console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["stream_to_console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django_auth_ldap": {
            "handlers": ["stream_to_console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "out-mail.geant.org"
# EMAIL_HOST_USER = "encompass@host.geant.org"   # this is used for authentication if needed
# EMAIL_HOST_PASSWORD = "your_password_here" # this is used for authentication if needed
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = "encompass@host.geant.org"
