services:
  encompass:
    profiles:
      - encompass
      - all
    env_file:
      - vars
    dns:
      - 83.97.93.200
    restart: unless-stopped
    container_name: encompass
    build:
      context: .
      dockerfile: Dockerfiles/encompass
      args:
        APP_DEBUG: "true"
    ports:
      - "8080:8080"  # enCompass UI
      - "8081:8081"  # ENC
      - "8443:8443"  # enCompass UI SSL
      - "8444:8444"  # ENC SSL

  encapsule:
    profiles:
      - encapsule
      - all
    env_file:
      - vars
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfiles/encapsule
      args:
        APP_DEBUG: "true"
    ports:
      - "9081:8081"  # enCapsule ENC API
      - "9444:8444"  # enCapsule ENC API SSL
