services:
  encompass:
    env_file:
      - vars
    dns:
      - 83.97.93.200
      - 8.8.8.8
    restart: unless-stopped
    container_name: encompass
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DEBUG: "true"
    ports:
      - "8080:8080"  # enCompass UI
      - "8081:8081"  # ENC
      - "8443:8443"  # enCompass UI SSL
      - "8444:8444"  # ENC SSL
