[program:haproxy]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=unexpected
exitcodes=0
startsecs=0  # Don't restart if the process exits immediately, which is the case in single-node mode.
stopasgroup=true
user=root
priority=4
directory=/
command=/usr/local/bin/haproxy.sh
