#!/usr/bin/bash
#
# Start HAProxy only when a config was generated by entrypoint.sh (multi-node mode).
# In single-node mode no config file exists, and this script exits cleanly so
# supervisord does not restart it.
#
set -e

if [ ! -f /etc/haproxy/haproxy.cfg ]; then
    echo "==> HAProxy: no config found (single-node mode), skipping"
    exit 0
fi

echo "==> HAProxy: starting for Galera cluster..."
exec /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -db
