[program:enc]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
user=root
directory=/code/enc
command=gunicorn --log-level info --bind unix:/run/enc.sock -t 100 --worker-tmp-dir=/dev/shm -w 3 --threads=3 -k gthread enc:app
