[program:static]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
user=root
directory=/code/static
command=gunicorn --log-level info --bind unix:/run/static.sock -t 100 --worker-tmp-dir=/dev/shm -w 3 --threads=3 -k gthread static:app
