[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[unix_http_server]
file = /run/supervisor.sock
chmod = 0700
username = dummy
password = dummy

[supervisorctl]
serverurl = unix:///run/supervisor.sock
username = dummy
password = dummy
