[program:encapsule]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
stopasgroup=true
user=root
priority=10
directory=/code/encapsule
command=/usr/local/bin/encapsule.sh
